spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: fazeal-logistics
  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888}
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1000
    leaseExpirationDurationInSeconds: 2000
    preferIpAddress: true
    hostname: ${HOST_NAME}